import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { FC, useEffect, useState } from "react";
import Loading from "./Loading/Loading";

const inter = Inter({ subsets: ["latin"] });

const Home: FC = () => {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    // setTimeout(() => {
    //   setLoading(false)
    // }, 5000);
  }, []);

  let LoadingFa =()=>{
    setLoading(false)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <div className={styles.Loading}>
          <Loading  onClick={LoadingFa}/>
          
        </div>
      ) : (
        <h1>ernis</h1>
      )}
    </>
  );
};
export default Home;
